Fix `is_instance` pricing and relevant tests
IBM-Cloud/infracost pull request #199
Opened 2024-09-25 06:43 UTC by luisarojas

2024-09-25 18:03 UTC, hiltol requested changes

2024-09-25 18:03 UTC, hiltol commented on internal/providers/terraform/ibm/is_instance.go
> +	if len(bootVolumeParse) > 0 {
if a boot volume isn't sepcified, then a default one will be created and will need to be added as a cost component. see https://cloud.ibm.com/docs/vpc?topic=vpc-creating-virtual-servers&interface=ui 
<img width="767" alt="Screenshot 2024-09-25 at 1 59 03 PM" src="https://github.com/user-attachments/assets/e278e3e7-6b40-45e3-9c68-29ce8e314392">

2024-10-04 23:36 UTC, luisarojas commented
* I changed the service to `is.reservation` and the charge unit to `RESERVATION_HOURS_HOURLY`, but I didn't find one for dedicated host. I assumed (from the previous charge units) that when dedicated the price would be 0, so that's what I set it to.
* It also seems that a few profiles are not found in the new service ID `is.reservation`:
    - `ibm_is_instance.vsi[\"bx3dc-96x480\"]`
    - `ibm_is_instance.vsi[\"bx3dc-32x160\"]`
    - `ibm_is_instance.vsi[\"cx3dc-96x240\"]`
    - `ibm_is_instance.vsi[\"cx3dc-32x80\"]`
    - `ibm_is_instance.vsi[\"cx3dc-2x5\"]`
    - `ibm_is_instance.vsi[\"cx3dc-8x20\"]`
    - `ibm_is_instance.vsi[\"bx3dc-48x240\"]`
    - `ibm_is_instance.vsi[\"bx3dc-16x80\"]`
    - `ibm_is_instance.vsi[\"bx3dc-8x40\"]`
    - `ibm_is_instance.vsi[\"cx3dc-128x320\"]`
    - `ibm_is_instance.vsi[\"vx2d-44x616\"]`
    - `ibm_is_instance.vsi[\"cx3dc-24x60\"]`
    - `ibm_is_instance.vsi_boot_volume[\"cx3dc-128x320\"]`

2024-10-10 20:05 UTC, hiltol commented
> * bx3dc-96x480

instance profiles that end with the letter c stands for confidential computing profiles and are listed under the "is.instance" service
<img width="1120" alt="Screenshot 2024-10-10 at 4 05 05 PM" src="https://github.com/user-attachments/assets/4405355d-260d-4910-81a6-9e92f47ee405">

2024-10-10 20:20 UTC, hiltol approved these changes

2024-10-10 20:20 UTC, merged