feat(ibm): add container_vpc_cluster
IBM-Cloud/infracost pull request #4
Opened 2022-07-07 17:52 UTC by balazs-marjan

The tests seem wonky, it might be because I included the other modules in the vpc clusters and pools.

The actual query based ones seem to work fine.

2022-07-12 12:49 UTC, hiltol requested changes

2022-07-12 13:07 UTC, balazs-marjan commented on internal/resources/ibm/container_vpc_cluster.go
> +		attributeFilters = append(attributeFilters, &schema.AttributeFilter{
If I don't pass it in, ocp and no ocp options. The backend will handle the null check, you can check the `filterToCondition` function

2022-07-12 13:07 UTC, balazs-marjan commented on internal/resources/ibm/container_vpc_worker_pool.go
> +		{Key: "operatingSystem", Value: strPtr(operatingSystem)},
ok

2022-07-12 13:07 UTC, balazs-marjan commented on internal/resources/ibm/ibm_is_vpc.go
> -		Unit:            "Instance",
ok

2022-07-12 13:08 UTC, balazs-marjan commented on internal/providers/terraform/ibm/testdata/ibm_is_vpc_test/ibm_is_vpc_test.golden
> - └─ VPC us-south               1  Instance         $0.00
ok

2022-07-12 13:08 UTC, balazs-marjan commented on internal/resources/ibm/container_vpc_cluster.go
> +		{Key: "operatingSystem", Value: strPtr(operatingSystem)},
ok

2022-07-12 16:06 UTC, balazs-marjan commented on internal/providers/terraform/ibm/testdata/ibm_is_vpc_test/ibm_is_vpc_test.golden
> - └─ VPC us-south               1  Instance         $0.00
resolved in the other PR

2022-07-15 13:29 UTC, sonkatomi approved these changes

2022-07-18 22:26 UTC, hiltol approved these changes

2022-07-22 08:32 UTC, merged